### ISSUE TITLE
Variable $FileServer

### ISSUE THREAD

**Issue by msounhein** [ofelman/HPIA-Repository-Downloader#1]
I believe that 

https://github.com/ofelman/HPIA-Repository-Downloader/blob/2e48b0d2f62114b611045d2272ef107ed347bc9b/HPIARepo_ini.ps1#L67

 should be $FileServerName and not $FileServer. 

See
https://github.com/ofelman/HPIA-Repository-Downloader/blob/2e48b0d2f62114b611045d2272ef107ed347bc9b/HPIARepo_Downloader_1.80.ps1#L360
and See
https://github.com/ofelman/HPIA-Repository-Downloader/blob/2e48b0d2f62114b611045d2272ef107ed347bc9b/HPIARepo_Downloader_1.80.ps1#L379

Once I changed that along with the $SiteCode listed below then it did connect and the packages were updated in SCCM

https://github.com/ofelman/HPIA-Repository-Downloader/blob/2e48b0d2f62114b611045d2272ef107ed347bc9b/HPIARepo_Downloader_1.80.ps1#L191

Cool, and very useful, script!

Thanks,
Michael Sounhein

**Comment by ofelman** [comment]
thank you, file updated

**Comment by msounhein** [comment]
Thanks for fixing that.
