### ISSUE TITLE
W11 version 23H2

### ISSUE THREAD

**Issue by kingskawn** [ofelman/HPIA-Repository-Downloader#13]
Is it possible to update the script to be able to download drivers for Windows 11 23H2 ?

**Comment by ofelman** [comment]
all you need to do is modify the line in HPIARepo_ini.ps1 to read like this;

$v_OSVALID11 = @("21H2", "22H2", "23H2")

and restart the downloader script

**Comment by kingskawn** [comment]
Thanks but already did this. I was too quick in creating a request here, sorry 😅😆
