### ISSUE TITLE
GUI Issues with High DPI screens...

### ISSUE THREAD

**Issue by krikk** [ofelman/HPIA-Repository-Downloader#2]
first: thx for the nice script... but i am using a 4k display with display scaling set to 150 % and the GUI is all messed up like this:

![image](https://user-images.githubusercontent.com/5165445/130023978-a4731d00-c382-433c-9e65-f8f2c6fdf937.png)

is there any simple way to fix this...?

**Comment by ofelman** [comment]
not easily and unfortunately, my ability to work on a UI issue such as this one is low... apologize... maybe some day
