### ISSUE TITLE
Repository Filter Structure Changed?

### ISSUE THREAD

**Issue by prrobinson81** [ofelman/HPIA-Repository-Downloader#3]
We're testing for a single model at the moment, 861F, however regardless of which model we select, if we tick all the boxes, synch the repository, then close and re-open the UI, the SysId value is shown as `System.Object[]`.  If we take a look inside the INI file the sysid is now shown 4 times inside each entry in `$HPModelsTable`.

I believe the culprit is the filters in `repository.json` - instead of having a single filter, with multiple space-delimited values in the category entry, we now see 4 filters, with one category per entry.  This is also the case if we manually run `(get-repositoryinfo).Filters` inside the repository.

By way of example, lines 1314-1320 show an example filter:
```
    ### example filter returned by 'get-repositoryinfo' CMSL command: 
    ###
    ### platform        : 8438
    ### operatingSystem : win10:2004 win10:2004
    ### category        : BIOS firmware
    ### releaseType     : *
    ### characteristic  : ssm
```
Whereas what we're seeing is:
```
    ### platform        : 8438
    ### operatingSystem : win10:2004 win10:2004
    ### category        : BIOS
    ### releaseType     : *
    ### characteristic  : ssm
    ###
    ### platform        : 8438
    ### operatingSystem : win10:2004 win10:2004
    ### category        : firmware
    ### releaseType     : *
    ### characteristic  : ssm
```
We've updated the HPCMSL module with no change, and we're using script 1.87.

Sorry if this is the wrong way to report an error, and of course am happy to help debug with tests/examples etc.

**Comment by ofelman** [comment]
let me check the code and see if i can find the problem
