### ISSUE TITLE
Multiple OS Versions

### ISSUE THREAD

**Issue by MSauerland** [ofelman/HPIA-Repository-Downloader#4]
Hello,

its more a question as an Issue, we have a Infrastruckture with different OS versions of W10. Is it possible to select multiple versions like 1909 20H2 and 21H2 to download all compatible Drivers etc.?

Kind regards
Michael

**Comment by ofelman** [comment]
yes, but not at one time... you can select one OS version and Sync, then
check the 'Keep prev settings'  and select the next OS version... when you
sync the previous filters will not be erased and there will be filters for
both OS versions in the repository

Hope this helps
