### ISSUE TITLE
Support for windows 10 21h1

### ISSUE THREAD

**Issue by thewebserverisdown** [ofelman/HPIA-Repository-Downloader#5]
Repository sync fails could not find a data file for this platform for 21H1
![image](https://user-images.githubusercontent.com/4382362/136719347-d9e00527-c545-4fe5-b221-efe70dbc323b.png)

ini
set to 
$v_OSVALID = @("1809", "1909", "2009", "2104")
$v_OSVER = "2104"

if set top 21H1 powershell gives a interger datatype error.
How to configure so that 2104 softpaqs will download?
is it generally okay to user 2009 version string instead?

**Comment by ofelman** [comment]
this should work

$v_OSVALID = @("1809", "1909", "2009", "21H1")
$v_OSVER = "21H1"

**Comment by thewebserverisdown** [comment]
![image](https://user-images.githubusercontent.com/4382362/138974786-e7277e78-a867-4919-b6b6-3c22e35b6971.png)
![image](https://user-images.githubusercontent.com/4382362/138974828-250568f9-a9f6-4cbe-af20-ca3b2a18fa83.png)
Does not seem to work my friend due to datatype error expecting integer but 21h1 contains h char?

**Comment by thewebserverisdown** [comment]
Updated to 1.87 of the code and it seems to work now.
I note that OS NOT SUPPORTED seems to be returned for all the models - its that correct? 
![image](https://user-images.githubusercontent.com/4382362/138976812-3b90d411-5f1a-4795-a949-94bd0c623ae1.png)

**Comment by thewebserverisdown** [comment]
deleting the old powerhsel HPCSML C:\Program Files\WindowsPowerShell\Modules
and then downloading 1.6.3  fixed the issues for me and is all working.

It Seemed to produce errors or different result for  version prior to 1.6.3 when running the command Get-SoftpaqList -Platform 83b2 -Os win10 -OsVer "21H1"

**Comment by ofelman** [comment]
Correct... 2021 versions are now updated in the INI file and match those that our Softpaq CVA files use, e.g., 21H1 and 21H2... try using the latest version 1.92.02
