### ISSUE TITLE
Unable to run using commands using v1.90

### ISSUE THREAD

**Issue by sean-firmston** [ofelman/HPIA-Repository-Downloader#6]
I'm very new to using the HPIA Repository Downloader, downloaded it yesterday, so hopefully I'm not missing something here but I've been using the GUI version of v1.90 and creating the repository however if I try and run it with command line switches it does nothing.

Looking at the code I see that line 3024 launches the sync_repos function with a single parameter:

    if ( $PSBoundParameters.Keys.Contains('Sync') ) { sync_repos $Script:v_CommonRepo }

However the sync_repos function looks to require two parameters:

Function Sync_Repos {
[CmdletBinding()]
	param( $pGrid, $pCommonRepoFlag )

Not sure if this is the reason why it will not run from the command line for me but it was the only thing I could see when looking at the code.

Thanks

Sean

**Comment by ofelman** [comment]
you are correct... was a coding error... try the latest version on GitHub, 1.92.02
